// ============================================================
//  COMANDOS DE MENU
//  Recebe ctx padrao e envia o menu como mensagem
// ============================================================
import config from '../config.js'
import { buildMenu, botHeader, botFooter } from '../lib/utils.js'

export async function handleMenu(ctx) {
  const { sock, cmd, args, groupId, grpSettings } = ctx

  const reply = async (text) => sock.sendMessage(groupId, { text })

  // Prefixo que sera exibido nos menus
  const p = grpSettings?.prefix || config.prefix || '#'

  const menus = {
    menu: {
      title: 'MENU PRINCIPAL',
      items: [
        `${p}menu figurinhas`,
        `${p}menu brincadeiras`,
        `${p}menu efeitos`,
        `${p}menu adm`,
        `${p}menu gold`,
        `${p}menu downloads`,
        `${p}menu info`,
        `${p}menu jogos`,
        `${p}menu grupo`,
        `${p}menu anime`,
        `${p}menu logos`,
        `${p}menu sticker`,
        `${p}menu marcar`,
        `${p}menu audio`,
        `${p}menu dono`,
        `${p}menu vip`,
        `${p}listanegra`,
        `${p}admins`,
        `${p}rankativos`,
        `${p}rankfigurinhas`,
        `${p}rankgold`,
        `${p}ranklevel`,
        `${p}status`,
        `${p}ping`,
        `${p}perfil`,
      ],
    },

    figurinhas: {
      title: 'MENU FIGURINHAS',
      items: [
        `${p}s / ${p}f - Criar figurinha`,
        `${p}take - Roubar figurinha`,
        `${p}rgtake <pack> <autor> - Registrar take`,
        `${p}rmtake - Remover take`,
        `${p}mytake - Ver seu take`,
        `${p}ttp <texto> - Texto para figurinha`,
        `${p}ttp2 / ttp3 / ttp4 / ttp5 / ttp6 - Cores`,
        `${p}attp <texto> - Texto animado`,
        `${p}attp2 / attp3 / attp4 - Variantes`,
        `${p}toimg - Figurinha para imagem`,
        `${p}togif - Figurinha para GIF`,
        `${p}tomp4 - Figurinha para MP4`,
        `${p}fig - Figurinha aleatoria`,
        `${p}figanime - Fig anime`,
        `${p}figmeme - Fig meme`,
        `${p}figroblox - Fig roblox`,
        `${p}figemoji - Fig emoji`,
        `${p}figcoreana - Fig coreana`,
        `${p}figraiva - Fig raiva`,
        `${p}figengracada - Fig engracada`,
        `${p}figdesenho - Fig desenho`,
        `${p}rename <pack/autor> - Renomear`,
        `${p}sfundo - Remover fundo`,
        `${p}smartsticker - Sticker inteligente`,
        `${p}qc <texto> - Quote chat`,
        `${p}qc1 / qc2 - Variantes`,
        `${p}emoji <emoji> - Emoji para figurinha`,
        `${p}emoji-mix <e1> <e2> - Misturar emojis`,
        `${p}addstickercmd <nome> - Salvar figurinha cmd`,
        `${p}getstickercmd <nome> - Usar figurinha salva`,
        `${p}delstickercmd <nome> - Remover figurinha salva`,
        `${p}liststickerscmd - Listar figurinhas salvas`,
        `${p}autofigu - Auto figurinha ON/OFF`,
      ],
    },

    brincadeiras: {
      title: 'MENU BRINCADEIRAS',
      items: [
        `${p}ppt <pedra/papel/tesoura> - PPT vs Bot`,
        `${p}ppt2 @user <escolha> - PPT vs Player`,
        `${p}akinator - Akinator`,
        `${p}damas @user - Jogo de damas`,
        `${p}jogodavelha @user - Jogo da velha`,
        `${p}jv <1-9> - Jogada da velha`,
        `${p}iniciar_forca - Jogo da forca`,
        `${p}rv <letra> - Jogar forca`,
        `${p}roleta - Roleta russa`,
        `${p}fakemsg @user <msg> - Mensagem falsa`,
        `${p}eujaeununca - Eu ja e eu nunca`,
        `${p}porcentagem <algo> - Porcentagem`,
        `${p}chance <algo> - Chance de algo`,
        `${p}sorte - Sua sorte do dia`,
        `${p}rankgay - Rank gay`,
        `${p}rankgado - Rank gado`,
        `${p}rankcorno - Rank corno`,
        `${p}rankgostoso - Rank gostoso`,
        `${p}rankgostosa - Rank gostosa`,
        `${p}rankkenga - Rank kenga`,
        `${p}rankhetero - Rank hetero`,
        `${p}rankotaku - Rank otaku`,
        `${p}gadometro - Gadometro`,
        `${p}signo <signo> - Horoscopo`,
        `${p}pergunta - Pergunta aleatoria`,
        `${p}sn - Sim ou Nao`,
        `${p}cantadas - Cantada aleatoria`,
        `${p}fatos - Fato aleatorio`,
        `${p}conselho - Conselho aleatorio`,
        `${p}conselhobiblico - Verso biblico`,
        `${p}duelo @user - Iniciar duelo`,
        `${p}votar_duelo 1/2 - Votar no duelo`,
        `${p}iniciar_votacao <pergunta> - Criar votacao`,
        `${p}votar sim/nao - Votar`,
        `${p}terminar_votacao - Encerrar votacao`,
        `${p}anagrama - Jogo de anagrama`,
        `${p}revelar_anagrama - Revelar anagrama`,
        `${p}imc <peso> <altura> - Calcular IMC`,
        `${p}ceu - Chance de ir pro ceu`,
        `${p}inferno - Chance de ir pro inferno`,
        `${p}simi <texto> - Perguntar ao bot`,
        `${p}bot <texto> - Falar com o bot`,
      ],
    },

    efeitos: {
      title: 'MENU EFEITOS',
      items: [
        `${p}kiss @user - Beijo (com gif)`,
        `${p}ship @user - Ship (com %)`,
        `${p}slap @user - Tapa (com gif)`,
        `${p}triggered - Triggered`,
        `${p}jail - Na prisao`,
        `${p}wasted - Wasted`,
        `${p}blur - Borrar imagem`,
        `${p}greyscale - Preto e branco`,
        `${p}sepia - Efeito sepia`,
        `${p}invert - Inverter cores`,
        `${p}clown - Palhaco`,
        `${p}beautiful - Beautiful`,
        `${p}upscale / hd - Melhorar imagem`,
        `${p}circulo - Imagem em circulo`,
        `${p}metadinha @user - Metadinha`,
        `${p}totext - Msg para texto`,
        `${p}menu audio - Ver efeitos de audio`,
        `${p}menu logos - Ver efeitos de texto`,
      ],
    },

    audio: {
      title: 'MENU EFEITOS DE AUDIO',
      items: [
        `${p}grave - Efeito grave`,
        `${p}grave2 - Efeito grave 2`,
        `${p}bass - Efeito bass`,
        `${p}bass2 - Bass pesado`,
        `${p}bass3 - Bass extremo`,
        `${p}estourar - Estourar audio`,
        `${p}estourar2 - Estourar audio 2`,
        `${p}fast - Audio rapido`,
        `${p}slow - Audio lento`,
        `${p}speedup - Acelerar`,
        `${p}esquilo - Voz de esquilo`,
        `${p}vozmenino - Voz de menino`,
        `${p}reverse - Audio ao contrario`,
        `${p}deep - Voz grave/profunda`,
        `${p}fat - Voz grossa`,
        `${p}alto - Volume alto`,
        `${p}audiolento - Audio lento`,
        `${p}audiocontrario - Audio ao contrario`,
        `${p}videocontrario - Video ao contrario`,
        `${p}videolento - Video lento`,
        `${p}videorapido - Video rapido`,
      ],
    },

    adm: {
      title: 'MENU ADMINISTRACAO',
      items: [
        `${p}ban @user - Banir membro`,
        `${p}add <numero> - Adicionar membro`,
        `${p}advertir @user - Advertir`,
        `${p}checkwarnings @user - Ver advertencias`,
        `${p}removewarnings @user - Remover adv`,
        `${p}clearwarnings - Limpar todas adv`,
        `${p}advertidos - Listar advertidos`,
        `${p}resetavisos - Resetar todos avisos`,
        `${p}mute @user - Silenciar`,
        `${p}desmute @user - Dessilenciar`,
        `${p}promover @user - Promover a admin`,
        `${p}rebaixar @user - Rebaixar de admin`,
        `${p}cargo @user <cargo> - Atribuir cargo`,
        `${p}tagall - Marcar todos`,
        `${p}totag <msg> - Marcar com mensagem`,
        `${p}hidetag <msg> - Marcar oculto`,
        `${p}linkgp - Link do grupo`,
        `${p}nomegp <nome> - Mudar nome`,
        `${p}descgp <desc> - Mudar descricao`,
        `${p}fotogp - Mudar foto (marcar img)`,
        `${p}fechargp - Fechar grupo`,
        `${p}abrirgp - Abrir grupo`,
        `${p}deletar - Apagar msg marcada`,
        `${p}sorteio - Sortear membro`,
        `${p}banghost - Banir sem foto de perfil`,
        `${p}banfakes - Banir numeros fakes`,
        `${p}inativos [dias] - Ver membros inativos`,
        `${p}nuke - Remover todos membros (dona)`,
        `${p}listanegra <num> - Add lista negra`,
        `${p}tirardalista <num> - Remover lista negra`,
        `${p}listaban - Ver lista negra`,
        `${p}listabranca @user - Add lista branca`,
        `${p}listabranca list - Ver lista branca`,
        `${p}rmlistabranca @user - Remover lista branca`,
        `${p}aceitar - Aceitar solicitacoes`,
        `${p}anotar <texto> - Fazer anotacao`,
        `${p}anotacoes - Ver anotacoes`,
        `${p}rmnota <id> - Remover nota`,
        `${p}status - Status do grupo`,
        `${p}atividades - Log de atividades`,
        `${p}regras - Ver regras do grupo`,
        `${p}permissoes - Ver niveis de permissao`,
        `${p}bemvindo - Ativar boas vindas ON/OFF`,
        `${p}bemvindo2 - Boas vindas 2 ON/OFF`,
        `${p}antilink - Anti link ON/OFF`,
        `${p}advlink - Adv por link ON/OFF`,
        `${p}antilinkgp - Anti link de grupo ON/OFF`,
        `${p}advlinkgp - Adv link grupo ON/OFF`,
        `${p}antifake - Anti fake ON/OFF`,
        `${p}antiflood - Anti flood ON/OFF`,
        `${p}advflood - Adv por flood ON/OFF`,
        `${p}antipalavra - Anti palavrao ON/OFF`,
        `${p}antibots - Anti bots ON/OFF`,
        `${p}antimarcar - Anti marcacao ON/OFF`,
        `${p}antiimg - Anti imagem ON/OFF`,
        `${p}antivideo - Anti video ON/OFF`,
        `${p}antiaudio - Anti audio ON/OFF`,
        `${p}antidoc - Anti documento ON/OFF`,
        `${p}antisticker - Anti sticker ON/OFF`,
        `${p}anticatalogo - Anti catalogo ON/OFF`,
        `${p}anticontato - Anti contato ON/OFF`,
        `${p}antiloc - Anti localizacao ON/OFF`,
        `${p}antinotas - Anti notas ON/OFF`,
        `${p}anticallgp - Anti call ON/OFF`,
        `${p}addpalavra <palavra> - Add palavra proibida`,
        `${p}delpalavra <palavra> - Remover palavra`,
        `${p}listapalavrao - Listar palavras`,
        `${p}limparpalavras - Limpar palavras`,
        `${p}so_adm - Modo so adm ON/OFF`,
        `${p}autobaixar - Auto download ON/OFF`,
        `${p}autosticker - Auto sticker ON/OFF`,
        `${p}x9viewonce - Revelar view once ON/OFF`,
        `${p}x9adm - X9 admin ON/OFF`,
        `${p}multiprefixo - Multi prefixo ON/OFF`,
        `${p}prefixos - Ver prefixos ativos`,
        `${p}add_prefixo <p> - Adicionar prefixo`,
        `${p}del_prefixo <p> - Remover prefixo`,
        `${p}autoban - Auto ban lista negra ON/OFF`,
        `${p}limittexto - Limite texto ON/OFF`,
        `${p}limitecaracteres <n> - Definir limite`,
        `${p}tempocmd <seg> - Cooldown de comandos`,
        `${p}bloquearcmd <cmd> - Bloquear comando`,
        `${p}liberarcmd <cmd> - Liberar comando`,
        `${p}modoparceria - Modo parceria ON/OFF`,
        `${p}simih - Simi ON/OFF`,
        `${p}autoresposta - Auto resposta ON/OFF`,
        `${p}modorpg - Modo RPG ON/OFF`,
        `${p}modogamer - Modo Gamer ON/OFF`,
        `${p}nsfw - NSFW ON/OFF`,
        `${p}legendabv <texto> - Legenda boas vindas`,
        `${p}legendasaiu <texto> - Legenda saida`,
        `${p}setmsgban <texto> - Msg de ban`,
        `${p}mensagem-automatica - Agendar msg`,
        `${p}listar-mensagens-automaticas - Ver agendadas`,
        `${p}limpar-mensagens-automaticas - Limpar agendadas`,
        `${p}opengp <hora> - Abrir automatico`,
        `${p}closegp <hora> - Fechar automatico`,
        `${p}rm_opengp - Remover horarios auto`,
        `${p}add_parceria <link> - Add parceria`,
        `${p}del_parceria <link> - Remover parceria`,
        `${p}parceria - Ver parcerias`,
        `${p}addcmdgold <cmd> <custo> - Cmd com gold`,
        `${p}rmcmdgold <cmd> - Remover custo gold`,
        `${p}addgold @user <qtd> - Dar gold`,
        `${p}addxp @user <qtd> - Dar XP`,
        `${p}zerar_gold @user - Zerar gold`,
        `${p}resetlevel - Resetar niveis`,
      ],
    },

    gold: {
      title: 'MENU GOLD',
      items: [
        `${p}gold - Ver seu gold`,
        `${p}gold @user - Ver gold de alguem`,
        `${p}rankgold - Ranking de gold`,
        `${p}doargold @user <qtd> - Doar gold`,
        `${p}minerar_gold - Minerar gold`,
        `${p}roubargold @user - Roubar gold`,
        `${p}vingancagold @user - Vinganca gold`,
        `${p}daily - Gold diario`,
        `${p}lojagold - Loja de gold`,
        `${p}ccgold <n> - Comprar da loja`,
        `${p}cassino <qtd> - Cassino`,
        `${p}apostargold <qtd> - Apostar`,
        `${p}doublegold <qtd> - Double`,
        `${p}jackpotgold <qtd> - Jackpot`,
        `${p}roletadasorte <qtd> - Roleta da sorte`,
        `${p}aviatorgold <qtd> - Aviator`,
        `${p}caixamisteriosagold - Caixa misteriosa`,
        `${p}quiznumero - Quiz numero`,
        `${p}sorteiogold [qtd] - Sorteio gold`,
        `${p}bolaogold - Bolao gold`,
        `${p}rankingjogosgold - Rank jogos gold`,
        `${p}premium - Ver status premium`,
      ],
    },

    downloads: {
      title: 'MENU DOWNLOADS',
      items: [
        `${p}play <nome> - Baixar musica (audio)`,
        `${p}playvideo <nome> - Baixar video`,
        `${p}playdoc <nome> - Baixar como documento`,
        `${p}tiktok <url> - Baixar TikTok video`,
        `${p}tiktok_audio <url> - TikTok audio`,
        `${p}instagram <url> - Baixar Instagram`,
        `${p}insta_audio <url> - Instagram audio`,
        `${p}twitter <url> - Baixar Twitter`,
        `${p}twitter_audio <url> - Twitter audio`,
        `${p}facebook <url> - Baixar Facebook`,
        `${p}face_audio <url> - Facebook audio`,
        `${p}threads_video <url> - Baixar Threads`,
        `${p}threads_audio <url> - Threads audio`,
        `${p}pinterest <texto/url> - Buscar Pinterest`,
        `${p}spotify <url> - Baixar Spotify`,
        `${p}soundcloud <url> - Baixar SoundCloud`,
        `${p}deezer <url> - Baixar Deezer`,
        `${p}kwai <url> - Baixar Kwai`,
        `${p}ifunny <url> - Baixar iFunny`,
        `${p}mediafire <url> - Baixar MediaFire`,
        `${p}ytmp4 <url> - YouTube MP4`,
        `${p}ytmp3 <url> - YouTube MP3`,
        `${p}ytsearch <nome> - Buscar no YouTube`,
        `${p}lyrics <nome> - Letra de musica`,
        `${p}gitclone <url> - Clonar repositorio`,
        `${p}tomp3 - Video/Audio para MP3`,
        `${p}download-link <url> - Baixar qualquer link`,
        `${p}statuszap - Postar no status`,
        `${p}shazam - Identificar musica`,
        `${p}transcrever - Audio para texto`,
        `${p}audio-menu - Menu de efeitos de audio`,
      ],
    },

    info: {
      title: 'MENU INFORMACOES',
      items: [
        `${p}info - Info do bot`,
        `${p}ping - Velocidade do bot`,
        `${p}dono - Info da dona`,
        `${p}idiomas - Idiomas disponiveis`,
        `${p}tabela - Info do grupo`,
        `${p}tabelagp - Info completa grupo`,
        `${p}gpinfo - Info grupo detalhada`,
        `${p}perfil - Seu perfil`,
        `${p}me - Suas estatisticas`,
        `${p}check @user - Info do membro`,
        `${p}admins - Lista de admins`,
        `${p}infocmd <cmd> - Info do comando`,
        `${p}configurar-bot - Como configurar`,
        `${p}eco <texto> - Repetir texto`,
        `${p}wame [@user] - Link wa.me`,
        `${p}tagme - Se auto-marcar`,
        `${p}clima <cidade> - Clima`,
        `${p}traduzir [lang] <texto> - Traduzir`,
        `${p}wikipedia <termo> - Buscar Wikipedia`,
        `${p}dicionario <palavra> - Dicionario`,
        `${p}calculadora <expr> - Calculadora`,
        `${p}cep <cep> - Buscar CEP`,
        `${p}ddd <ddd> - Info do DDD`,
        `${p}falar <texto> - Texto para voz`,
        `${p}afk [motivo] - Ficar ausente`,
        `${p}ativo - Voltar de AFK`,
        `${p}listarafk - Ver membros AFK`,
        `${p}apresentar <texto> - Se apresentar`,
        `${p}contar <texto> - Contar caracteres`,
        `${p}sender - Ver seu JID (debug)`,
        `${p}avalie <texto> - Avaliar o bot`,
        `${p}bug <texto> - Reportar bug`,
        `${p}sugestao <texto> - Enviar sugestao`,
        `${p}gemini <pergunta> - Perguntar IA`,
        `${p}gpt <pergunta> - Perguntar GPT`,
      ],
    },

    jogos: {
      title: 'MENU JOGOS',
      items: [
        `${p}ppt <escolha> - Pedra Papel Tesoura`,
        `${p}ppt2 @user <escolha> - PPT vs player`,
        `${p}jogodavelha @user - Jogo da velha`,
        `${p}jv <1-9> - Jogada da velha`,
        `${p}damas @user - Damas`,
        `${p}iniciar_forca - Jogo da forca`,
        `${p}rv <letra> - Jogar forca`,
        `${p}roleta - Roleta russa`,
        `${p}akinator - Akinator`,
        `${p}duelo @user - Iniciar duelo`,
        `${p}votar_duelo 1/2 - Votar duelo`,
        `${p}iniciar_votacao - Criar votacao`,
        `${p}votar sim/nao - Votar`,
        `${p}terminar_votacao - Encerrar votacao`,
        `${p}anagrama - Jogo de anagrama`,
        `${p}casamento @user - Pedir em casamento`,
        `${p}imc <peso> <altura> - Calcular IMC`,
      ],
    },

    grupo: {
      title: 'MENU GRUPO',
      items: [
        `${p}rankativos - Rank de ativos (msgs)`,
        `${p}rankativosg - Rank ativos gold`,
        `${p}checkativo @user - Checar atividade`,
        `${p}rankfigurinhas - Rank de figurinhas`,
        `${p}ultimosativos - Ultimos ativos`,
        `${p}rankinativo [dias] - Rank de inativos`,
        `${p}ranklevel - Rank de level/XP`,
        `${p}leveltemas - Temas de level`,
        `${p}novatos - Membros recentes`,
        `${p}listatm - Listar equipes`,
        `${p}rgtm <nome> - Criar equipe`,
        `${p}tirardatm <nome> - Remover equipe`,
        `${p}fazertm <nome> - Entrar em equipe`,
        `${p}listagp2 - Grupos do bot`,
        `${p}emcomum - Membros em comum`,
      ],
    },

    anime: {
      title: 'MENU ANIME',
      items: [
        `${p}animeinfo <nome> - Info do anime`,
        `${p}waifu - Waifu aleatoria`,
        `${p}neko - Neko aleatoria`,
        `${p}loli - Loli aleatoria`,
        `${p}megumin - Megumin`,
        `${p}goku - Goku`,
        `${p}nezuko - Nezuko`,
        `${p}makima - Makima`,
        `${p}kaguya - Kaguya`,
        `${p}nagatoro - Nagatoro`,
        `${p}sakura - Sakura`,
        `${p}hinata - Hinata`,
        `${p}akame - Akame`,
        `${p}gojo - Gojo`,
        `${p}shinobu - Shinobu`,
        `${p}anya - Anya`,
        `${p}komi - Komi`,
        `${p}muzan - Muzan`,
        `${p}mitsuri - Mitsuri`,
        `${p}yoruichi - Yoruichi`,
        `${p}rukia - Rukia`,
        `${p}fubuki - Fubuki`,
        `${p}pinterest <tema> - Buscar imagem`,
      ],
    },

    logos: {
      title: 'MENU LOGOS & EFEITOS DE TEXTO',
      items: [
        `${p}shadow <txt> - Efeito shadow`,
        `${p}neon <txt> - Efeito neon`,
        `${p}fire <txt> - Efeito fogo`,
        `${p}smoke <txt> - Efeito fumaca`,
        `${p}matrix <txt> - Efeito matrix`,
        `${p}blood <txt> - Efeito sangue`,
        `${p}lava <txt> - Efeito lava`,
        `${p}gelo <txt> - Efeito gelo`,
        `${p}3dgold <txt> - Efeito 3D gold`,
        `${p}rainbow <txt> - Efeito arco-iris`,
        `${p}carbon <txt> - Efeito carbon`,
        `${p}horror <txt> - Efeito horror`,
        `${p}berry <txt> - Efeito berry`,
        `${p}luxury <txt> - Efeito luxury`,
        `${p}toxic <txt> - Efeito toxico`,
        `${p}metalgold <txt> - Metal gold`,
        `${p}madeira <txt> - Efeito madeira`,
        `${p}blackpink <txt> - Efeito BlackPink`,
        `${p}narutologo <txt> - Logo Naruto`,
        `${p}hackneon <txt> - Hack neon`,
        `${p}demonfire <txt> - Demon fire`,
        `${p}thunder <txt> - Trovao`,
        `${p}natal <txt> - Efeito natal`,
        `${p}halloween <txt> - Halloween`,
        `${p}neve <txt> - Efeito neve`,
        `${p}areia <txt> - Efeito areia`,
        `${p}lapis <txt> - Efeito lapis`,
        `${p}vidro <txt> - Efeito vidro`,
        `${p}jeans <txt> - Efeito jeans`,
        `${p}ossos <txt> - Efeito ossos`,
        `(E muitos outros... use ${p}menu efeitos)`,
      ],
    },

    sticker: {
      title: 'MENU STICKER',
      items: [
        `${p}s - Criar sticker de imagem/video`,
        `${p}f - Criar sticker (alias)`,
        `${p}toimg - Sticker para imagem`,
        `${p}togif - Sticker para GIF`,
        `${p}tomp4 - Sticker para MP4`,
        `${p}take <pack> <autor> - Roubar sticker`,
        `${p}rgtake <pack> <autor> - Registrar take`,
        `${p}rmtake - Remover take`,
        `${p}mytake - Ver seu take`,
        `${p}rename <pack/autor> - Renomear`,
        `${p}attp <txt> - Texto animado`,
        `${p}ttp <txt> - Texto para sticker`,
        `${p}qc <txt> - Quote chat`,
        `${p}sfundo - Remover fundo`,
        `${p}emoji <emoji> - Emoji para sticker`,
        `${p}emoji-mix <e1> <e2> - Misturar emojis`,
      ],
    },

    marcar: {
      title: 'MENU MARCAR / INTERACOES',
      items: [
        `${p}lixo @user - Lixo`,
        `${p}lgbt @user - LGBT`,
        `${p}preso @user - Preso`,
        `${p}procurado @user - Procurado`,
        `${p}deletem @user - Delete`,
        `${p}morto @user - Morto`,
        `${p}borrar @user - Borrar`,
        `${p}matar @user - Matar`,
        `${p}beijo @user - Beijo`,
        `${p}tapa @user - Tapa`,
        `${p}chute @user - Chute`,
        `${p}abraco @user - Abraco`,
        `${p}corno @user - Corno`,
        `${p}gado @user - Gado`,
        `${p}gostoso @user - Gostoso`,
        `${p}gostosa @user - Gostosa`,
        `${p}gay @user - Gay`,
        `${p}feio @user - Feio`,
        `${p}bebado @user - Bebado`,
        `${p}sigma @user - Sigma`,
        `${p}hetero @user - Hetero`,
        `${p}golpe @user - Golpe`,
        `${p}enviarcachaca @user - Cachaca`,
        `${p}casamento @user - Casar`,
      ],
    },

    vip: {
      title: 'MENU VIP / PREMIUM',
      items: [
        `${p}premium - Ver status premium`,
        `${p}lojagold - Comprar VIP com gold`,
        `${p}ccgold <n> - Comprar item da loja`,
      ],
    },

    dono: {
      title: 'MENU DONO (APENAS DONA)',
      items: [
        `${p}bc <msg> - Broadcast para todos grupos`,
        `${p}join <link> - Entrar em grupo`,
        `${p}sairgp - Sair do grupo`,
        `${p}nuke - Remover todos membros`,
        `${p}addgold @user <qtd> - Dar gold`,
        `${p}addxp @user <qtd> - Dar XP`,
        `${p}zerar_gold @user - Zerar gold`,
        `${p}resetlevel - Resetar niveis`,
        `${p}listanegra <num> - Lista negra`,
        `${p}block @user - Bloquear`,
        `${p}permissoes - Ver permissoes`,
      ],
    },

    // Anime reactions (sub-menu sticker)
    reactions: {
      title: 'MENU REACOES ANIME',
      items: [
        `${p}hug - Abraco anime`,
        `${p}pat - Cafune anime`,
        `${p}cuddle - Aconchego anime`,
        `${p}cry - Chorar anime`,
        `${p}smile - Sorriso anime`,
        `${p}wave - Acenar anime`,
        `${p}blush - Corar anime`,
        `${p}dance - Dancar anime`,
        `${p}wink - Piscar anime`,
        `${p}poke - Cutucar anime`,
        `${p}bite - Morder anime`,
        `${p}bonk - Bonk anime`,
        `${p}yeet - Yeet anime`,
        `${p}smug - Smug anime`,
        `${p}highfive - High five anime`,
        `${p}cringe - Cringe anime`,
        `${p}happy - Feliz anime`,
        `${p}lick - Lamber anime`,
        `${p}nom - Nom anime`,
        `${p}awoo - Awoo anime`,
      ],
    },
  }

  // Resolve o sub-menu a partir do comando
  let subMenu = 'menu'

  if (cmd === 'menu') {
    // Se veio argumento como "menu figurinhas", extrai a chave
    subMenu = args[0]?.toLowerCase() || 'menu'
  } else if (cmd === 'configurarbot' || cmd === 'configurar-bot') {
    subMenu = 'adm'
  } else {
    // Comandos como "menufigurinhas" -> remove "menu" do inicio
    subMenu = cmd.replace('menu', '')
  }

  // Aliases para nomes com acento ou abreviacao
  const aliases = {
    fig: 'figurinhas',
    figurinhas: 'figurinhas',
    menufigurinhas: 'figurinhas',
    brincadeiras: 'brincadeiras',
    efeitos: 'efeitos',
    adm: 'adm',
    admin: 'adm',
    administracao: 'adm',
    gold: 'gold',
    download: 'downloads',
    downloads: 'downloads',
    baixar: 'downloads',
    info: 'info',
    informacoes: 'info',
    jogos: 'jogos',
    games: 'jogos',
    grupo: 'grupo',
    anime: 'anime',
    logos: 'logos',
    logo: 'logos',
    sticker: 'sticker',
    figurinha: 'sticker',
    marcar: 'marcar',
    interacoes: 'marcar',
    vip: 'vip',
    premium: 'vip',
    game: 'jogos',
    dono: 'dono',
    dona: 'dono',
    rpg: 'jogos',
    audio: 'audio',
    audios: 'audio',
    reacoes: 'reactions',
    reactions: 'reactions',
  }

  const resolvedKey = aliases[subMenu] || subMenu
  const menu = menus[resolvedKey] || menus['menu']

  await reply(buildMenu(menu.title, menu.items))
}
